### ISSUE TITLE
LoginUser mutation not returning user

### ISSUE THREAD

**Issue by spinzed** [yeeeeees/eventio-backend#5]
Returns message, success and accessToken but user is missing

**Comment by isakal** [comment]
Fixed with [this commit](https://github.com/yeeeeees/eventio-backend/commit/0bfbdb54d658aba3ecb80f9fff8b2126ea5c6b80)

Added user to return fields

**Comment by Spinzed** [comment]
Issue reopened: when entering invalid user data, the error message is returned: `"'NoneType' object has no attribute 'uuid'"`

**Comment by spinzed** [comment]
Issue reopened: when entering invalid user data, the error message is returned: "'NoneType' object has no attribute 'uuid'"

kliknija san krivi botun maloprije

**Comment by isakal** [comment]
Just noticed i forgot to put my identity injector inside the if statement, this will be fixed in commit with jwt implementation this evening.

**Comment by isakal** [comment]
Fixed in last merge.
